### ISSUE TITLE
hey, im getting this error

### ISSUE THREAD

**Issue by Faybo** [John-Weeks-Dev/tiktok-clone-api#1]
[nuxt] error caught during app initialization H3Error: Page not found: /api/get-random-users                                                                                                                           12:45:54  
    at Module.createError (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/h3/dist/index.mjs:128:15)
    at C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\pages\runtime\plugins\router.mjs:141:113
    at triggerAfterEach (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-router/dist/vue-router.mjs:3306:13)
    at file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-router/dist/vue-router.mjs:3209:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\pages\runtime\plugins\router.mjs:157:7
    at async createNuxtAppServer (C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\app\entry.mjs:30:7)
    at async default (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
    at async Object.renderToString (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/.nuxt/dev/index.mjs:717:21 {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Page not found: /api/get-random-users',
  __nuxt_error: true
}
[nuxt] error caught during app initialization H3Error: Page not found: /api/home                                                                                                                                       12:45:54
    at Module.createError (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/h3/dist/index.mjs:128:15)
    at C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\pages\runtime\plugins\router.mjs:141:113
    at triggerAfterEach (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-router/dist/vue-router.mjs:3306:13)
    at file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-router/dist/vue-router.mjs:3209:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\pages\runtime\plugins\router.mjs:157:7
    at async createNuxtAppServer (C:\Users\FAby\Desktop\RateTHE\RateThePlay\node_modules\nuxt\dist\app\entry.mjs:30:7)
    at async default (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/@nuxt/vite-builder/dist/runtime/vite-node.mjs:27:18)
    at async Object.renderToString (file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/node_modules/vue-bundle-renderer/dist/runtime.mjs:172:19)
    at async file:///C:/Users/FAby/Desktop/RateTHE/RateThePlay/.nuxt/dev/index.mjs:717:21 {
  statusCode: 404,
  fatal: false,
  unhandled: false,
  statusMessage: 'Page not found: /api/home',
  __nuxt_error: true
}

and this problem too

GET http://localhost:3000/sanctum/csrf-cookie 404 (Page not found: /sanctum/csrf-cookie)

**Comment by jdiggz** [comment]
I am having the same issues. Any fix for this?

Thanks in advance
